### ISSUE TITLE
Review utility of glossary

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/glossary#4]
* How were the terms selected? (CRM-2480)
  * Can ask @ColinMaudry to refresh my memory.
* How frequently is each term used in the documentation?
  * If rarely or never used, we can remove it from the glossary.
* Are the translated terms correct?
  * There are many warnings in Transifex. We should either fix translations, or update the glossary to remove warnings.

**Comment by ColinMaudry** [comment]
The rarity of a term is not a reason to exclude it. A term may be rare, but the choice of a translation over another may be key to help the translator catch certain nuances of the semantics. Synonyms are rarely strictly identical.

A term is a word or group of words for which the translation in a certain way particularly matters. It may be for consistency, but also, for instance, because it shows proximity with a culture rather than another (UK vs US, EU vs US, FR vs CA, ES vs LA, etc.).

For an organization, maintaining and publishing a glossary is way to say "here are the words we use", and it's usually not neutral.

**Comment by jpmckinney** [comment]
> The rarity of a term is not a reason to exclude it. A term may be rare, but the choice of a translation over another may be key to help the translator catch certain nuances of the semantics. Synonyms are rarely strictly identical.

Good point. We should at least check for words that never occur, and consider removing those.

**Comment by jpmckinney** [comment]
37 terms (out of 111, or 33%) are defined in both the glossary and OCDS:

* amendment
* amount
* award
* awardnotice
* bid
* biddingdocuments
* buyer
* classification
* contract
* contractnotice
* currency
* deprecated
* document
* electronicauction
* identifier
* implementation
* initiationtype
* item
* language
* milestone
* parties
* payee
* planning
* procurement
* procuringentity
* rationale
* record
* relationship
* reviewbody
* status
* subcontract
* supplier
* tag
* tender
* tenderer
* tendernotice
* works

This can lead to confusion if the definitions are not aligned (especially relevant with OCDS 1.2).

**Comment by jpmckinney** [comment]
While I agree with the aims and principles of having a glossary, in practice, we have not kept it up-to-date, have not followed the terminology process, and have not used the glossary to support translation.

As such, I will archive this repository. If/when we find the capacity to use a glossary properly, we can un-archive it.
